# Generated by Django 4.2.6 on 2023-10-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="Unknown", max_length=30, unique=True),
        ),
    ]
