# Generated by Django 4.2.6 on 2023-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
