# Generated by Django 4.2.6 on 2023-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_price",
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
