# Generated by Django 4.2.6 on 2023-10-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_product_new_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="new_price",
        ),
    ]
